general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Start screensaver after 10 hours
listener {
    timeout = 36000  # 10h
    on-timeout = pidof hyprlock || hyprlock
}

# Lock screen after 20 hours
listener {
    timeout = 72000  # 20h
    on-timeout = loginctl lock-session
}

# Turn off screen after 30 hours
listener {
    timeout = 108000  # 30h
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}